### ISSUE TITLE
Collaboration!

### ISSUE THREAD

**Issue by benjaminoakes** [newhavenio/newhavenio.github.io#1]
Hey guys, not sure where else to post this.  You're welcome to collaborate with me and @caseywatts on the Jekyll-based meetup site we've been maintaining.  We already have contributors from the IC and DC area.

Ours is: https://github.com/techcorridorio/techcorridorio.github.io

Not sure where @caseywatts has been contributing lately, but I know there's been some ongoing work that we need to pull in.

**Comment by caseywatts** [comment]
Yay! totally on board to collaborate >:D

Our plan is to help improve the Techcorridor.io Meetup Cards and Developer Cards until they meet as much of the same function as the current NewHaven.io site~

**Comment by alexwilkinson** [comment]
I really like the idea of switching to Jekyll. I suspect that would lower the barrier of contributing to the site immensely. I'm pretty busy this month quite honestly (started doing NaNoWriMo because I'm a masochist), but want to help out how I can!

**Comment by benjaminoakes** [comment]
It's been a help to us for sure.  5 contributors without me even really having to try.  (Let's see how high we can get that number to go!)

https://github.com/techcorridorio/techcorridorio.github.io/graphs/contributors

**Comment by caseywatts** [comment]
:tada: yayayay :D
