### ISSUE TITLE
"Interests" is spelled wrong on the Developer Cards

### ISSUE THREAD

**Issue by alexwilkinson** [newhavenio/newhavenio.github.io#15]
It's currently "intrests"

**Comment by alexwilkinson** [comment]
Thanks @lourinaldi! What do you think about have a PR workflow for these kinds of things? We don't have any developer guidelines so it was just something I was thinking about.

**Comment by lourinaldi** [comment]
@alexwilkinson a PR workflow is probably best. sorry to have pounced unannounced!

**Comment by treznick** [comment]
added an issue for this #17

**Comment by alexwilkinson** [comment]
@lourinaldi all good! ^_^

**Comment by sukima** [comment]
![Opps. my bad](https://jpmorgains.files.wordpress.com/2014/09/belated-notification-correcting-some-inadvertently-reported-misinformation.jpg)
