### ISSUE TITLE
Improve copy on homepage

### ISSUE THREAD

**Issue by jnimety** [newhavenio/newhavenio.github.io#47]

**Comment by lourinaldi** [comment]
## NewHaven.io is...

- [connecting and supporting](http://newhaven.io/blog/what-is-NewHavenIO/) New Haven’s technology community
- self-managed by volunteers (and always looking for more!)
- a 501(c)(6) non-profit
- about tech. all tech. your tech. 

## How can we help you?

If you’re a developer:
- [Community](https://www.meetup.com/newhavenio/) (socials)
- Grow: A chance to learn, to mentor, to present
- [Network](https://newhavenio-slackin.herokuapp.com/): find a new team, a new teammate, or a co-founder

If you’re a local software meetup group:
- Wider outreach, visibility
- Access to meeting spaces
- Logistical help

If you’re a software company:
- Recruiting, hiring
- A way for your employees to grow and learn

If you’re an entrepreneur:
- Sponsor a meetup (usually between $300 - $500), and we’ll let you pitch to the developers.

**Comment by lourinaldi** [comment]
https://github.com/newhavenio/newhavenio.github.io/pull/57
