### ISSUE TITLE
Add some loading state behavior to slackin button

### ISSUE THREAD

**Issue by treznick** [newhavenio/newhavenio.github.io#56]

**Comment by sukima** [comment]
There is loading state. It shows an animated GIF while it is waiting for Heroku to spin up. Did something break?

**Comment by treznick** [comment]
8bd493d235cdea4f9dfe299079f8dfd3424ad5ea removed the webcomponent, 002e0a7b348ce2a36b2c144515702a38e53e3629 removed the `onload`.

I think just having the `<script>` in the div is fine enough with an onload. Probably no need to have the webcomponent. I'm also happy to entertain more conversation. cc @NerdsvilleCEO

**Comment by sukima** [comment]
Can't help then. The reason for a webcomponent was so it should handle a loading state while the heroku app spun up. It was the premise of https://github.com/newhavenio/newhavenio.github.io/pull/27 I didn't know we reverted that PR.

**Comment by NerdsvilleCEO** [comment]
@treznick I wrote some code which changes it to not be a webcomponent and resizes the icon, if this PR handles and fixes this issue then I prefer using the webcomponent (I don't know how webcomponents work) otherwise we should merge the efforts I made to resize the icon

**Comment by NerdsvilleCEO** [comment]
oh crap I feel bad, I didn't realize that PR got merged... was trying to find that and just noticed... I will PM you @sukima and we can work to get the changes into a webcomponent, was running into issues w/ the script as a webcomponent

**Comment by sukima** [comment]
@NerdsvilleCEO you on the Slacks? You available tomorrow some time. Would be happy to pair during a lunch break.

**Comment by NerdsvilleCEO** [comment]
I think we can close this... @sukima I want to work with you on the PR #58, in the one that was reverted I had the button centered with also a drop down on page so they don't need to navigate away
