### ISSUE TITLE
Move hosting to Netlify

### ISSUE THREAD

**Issue by maxx1128** [newhavenio/newhavenio.github.io#65]
1) Included from the start, more convenient
2) No intermediary that would have an insecure connection
3) Flexibility to use any framework, not just Jekyll
4) Can deploy a working version to a hidden URL so it's easier to test and provide feedback before official launch
5) Can still host source code in Github repo for collaboration
6) If the build fails it'll fall back to the last successful build version, avoiding showing users a broken experience

**Comment by maxx1128** [comment]
Yep :)

**Comment by jnimety** [comment]
ok. If we're pre-compiling as a static site does it matter what frameworks are supported? Having a dev url is nice.

**Comment by maxx1128** [comment]
It's any framework really. You just set a branch, a build command, and it uses that output as the site. I'm currently using it with Gatsby, a static-site generator on react, and it compiles fine. They have docs for all frameworks they explicitly support, like Jekyll, but even if it doesn't list it then it should work fine.

**Comment by jnimety** [comment]
@treznick what do you mean?

@maxx1128 we're just now deploying Continuous Deployment (including build) via travis-ci so the hosting provider supporting our framework/build doesn't matter. This gives us ultimate flexibility on frameworks and build pipeline.

**Comment by treznick** [comment]
@jnimety I meant that moving where the records are listed requires some measure of coordination, but I may be mistaken on that

**Comment by treznick** [comment]
https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

Given that GH Pages now supports this, I'm going to close this issue. Thanks for looking into this @jnimety and @maxx1128
