### ISSUE TITLE
Remove the Developers page

### ISSUE THREAD

**Issue by maxx1128** [newhavenio/newhavenio.github.io#66]
It works fine and all, but I think so few people would seriously need a page like that, we're better off just removing it. Likely as part of the site redesign.

**Comment by danbernier** [comment]
I wouldn't go so far as to say that some folks have spammed us on that page, but...I think it's a good thing to remove.

**Comment by jhirbour** [comment]
I'm all for removing this page, I do think we should archive the content somewhere google drive? if anything just for the lulz

**Comment by jnimety** [comment]
It just pulls from meetup.com, right?

**Comment by sukima** [comment]
That page is nothing more then an AJAX (JSONP) to meetup.com. It was placed there to add more content and make the developer cards look nice (The meetup site was not nearly ass cool as seeing all the developer cards right on the website).

It is live and stays up-to-date my users on meetup.com adding/removing themselves as members to the newhaven.io meetup group.

> I do think we should archive the content somewhere

In the context of the data being fetched from an existing API I'm not sure I understand the value in this.

_Above is just some clarification. I am neither endorsing nor disagreeing to this issue._

**Comment by treznick** [comment]
Closing this because #123 removed the developers page.
