### ISSUE TITLE
Handoffs of nhv.io and newhaven.io ownership

### ISSUE THREAD

**Issue by ZachBeta** [newhavenio/newhavenio.github.io#68]
As we've been talking about the possibility of repointing the DNS in the current website refresh, we might use this opportunity to do the proper hand off of the domains to the organization somehow instead of held personally by two members of the board (@jnimety @kljensen )

**Comment by jnimety** [comment]
nhv.io needs to be transferred to dnsimple (kyle owns it and previous attempts to do a transfer have failed)

**Comment by jnimety** [comment]
I believe dnsimple supports shared management of domains, so we can probably just add @ZachBeta, @tom, etc as owners

**Comment by treznick** [comment]
I have a dnsimple account

**Comment by treznick** [comment]
closing since this was done.
