### ISSUE TITLE
Angular for filtering Developer profiles?

### ISSUE THREAD

**Issue by maxx1128** [newhavenio/newhavenio.github.io#7]
Really liked how you could filter developers by name on the Gumby site, was thinking we could use Angular to get the same effect. Ideally it would work out where:

- All developer names are visible from the start, but are collapsed to only show the name and a small icon. Is one half (or one third) of the width
- Can filter the name with an above search bar
- Clicking to expand a profile makes it expand to full width and show all their info.

Will look into how to use the Meetup API with Angular to get this effect.

**Comment by sukima** [comment]
The meetup API already uses jQuery. Does it need a full application framework? And if so what about something like Backbone which would be far less heavy lifting as Angular. Food for thought.

**Comment by maxx1128** [comment]
True, I just have more experience with Angular so my mind went there first. For that kind of live-filtering I was thinking a framework of some kind would be helpful since that's the kind of data-binding they were built for. Although with jQuery I should be able to get the same kind of results. Will be a little trickier but will also save a lot of time getting the API together with Angular, plus it lightens a lot of the Javascript load.

Will play around with it later today without Angular.
