### ISSUE TITLE
We have both package-lock.json and yarn.lock

### ISSUE THREAD

**Issue by jnimety** [newhavenio/newhavenio.github.io#75]
We need to settle on one package management solution. @NerdsvilleCEO did you intend to commit `package-lock.json`?

**Comment by bsutt123** [comment]
with npm version 6 coming out with a more security featured mindset, we might want to switch to npm, but I vote yarn and we remove the package-lock.json. But I am willing to be wrong if others feel strongly about npm versus yarn.

**Comment by sukima** [comment]
The difference is mainly aesthetics. They almost have feature parity at this point.

From what I know, NPM is needed when working with global modules (not applicable here) or with the NPM registry (like publishing, again not applicable here). Yarn on the other hand seems a little more friendly as a UI and a git friendly lock file. But really that doesn't mean much and is more opinion then fact.

In the long run it really is 6 in one hand and a half-dozen in another. Yarn is not going away soon and I'm willing to bet that when it does this site will be on some new fangled system beyond JS when the community pendulum swings back around again. Not to mention switching is a single commit easily accomplished.

Just to play devil's advocate, You can have both in a project. Though it does mean keeping the two in sync requires two commands and a lot of wasted disk I/O.

**Comment by treznick** [comment]
I mean, we can have two, but I'd say we should only use one. Fine to use
whichever.

**Comment by NerdsvilleCEO** [comment]
I would vote to use npm, and I think we should only have one in there to encourage usage thereof because I've seen issues on personal projects using both. I think whichever we decide to use we should remove the other

**Comment by jnimety** [comment]
we shouldn't have two, they resolve dependencies differently and the whole
point is to have deterministic dependencies and versions across dev and
production environments.

**Comment by treznick** [comment]
I prefer yarn because it got around to deterministic installs before npm,
but I'm happy to use either

**Comment by treznick** [comment]
then let's let the caprice of the random number generator drive the course
of our souls!

kidding. yarn it is :)
