### ISSUE TITLE
Remove developers page

### ISSUE THREAD

**Issue by bsutt123** [newhavenio/newhavenio.github.io#97]
I think that we can all agree that pagination for 1000+ developers is not the ideal solution. However, because Meetup has deigned it unnecessary to allow people to send them a search request that they implement as an api, it is currently impossible to display developers directly from meetup without just doing pagination with 40 people at a time. (edited)

We can display people i alphabetical order, which is the most useful for finding things, or we can display based on visited, which is probably more useful information overall but also has no possible organization, so finding someone specific would be much harder than alphabetical

My best solution was to scrap the data of name => id in ruby, generate a csv, and then send a csv along with the site. Then the CSV is parsed in the browser, and I'll give them a little search box, which will take my CSV and limit it to those searches, get the ids, then request the specific ids from meetup rather than just the group members

the problem is that that is a lot of work and stuff to send to the client for not a lot of value, so I wanted to get your guys opinion on whether or not we should just start to phase it out now, or if we made it better (and more csv heavy) then it might be worth keeping around

I think that something cool that could go in its place though is a kind of custom developers page, where we get to write about ourselves in markdown, and then we can do something similar to the blog where we render the list and then add links to the markdown file, which could be a neat way to highlight active members/members that want to be on the site.

**Comment by sukima** [comment]
I’ve done project similar with polling. The client side searching is super easy even with 10000 entries. And CSV is not needed if we use JSON which is not a huge ask to download asynchronously after the page loads.

However, you are correct in the value proposition. Adding a built tool to suck down the whole list would be cumbersome and having the client poll 40+ times might be mean to both the client browser and meetup. I have felt many times the developers at meetup don’t really live in this reality.

I am not apposed to removing the page. I would would also like to entertain any attempts at solving this even if nothing more than an academic exercise.

**Comment by maxx1128** [comment]
I'm in support of just scrapping it entirely. The work required to get an acceptable version of it working doesn't seem worth it to me.

**Comment by bsutt123** [comment]
Yeah to me isn't to much about could we do it so much as _should_ we do ti.

I also don't really think that its meeting the core goal of the website, which is to give new people a place to come to learn about us and want to join the community rather than a place for current members to find other members.

I think that creating a jekyll md page similar to blog that renders a list of individuals and then links to the self hosted markdown is what I think could actually satisfy the goals of making us more than just a random organization and instead put a face to the name.

We could start to add that now if it would be helpful for you @maxx1128  and then you can copy pasta the config over, or we can leave it to you to configure for the new site and well just kind of hobble along or remove this page for now.

**Comment by jnimety** [comment]
My vote is to remove the page. A quick poll in Slack a few weeks ago seemed to indicate that others felt the same way.

FWIW a previous iteration of the site had a self hosted developers database and we switched it to meetup.com for two reasons:

 1. People forget it's there and don't keep it updated.
 2. We wanted to move away from paid hosting, and at the time Heroku was clamping down on their free tier.

**Comment by bsutt123** [comment]
Sounds like a plan. I definitely think a full database is too much. I was thinking that we might use more of a "here are the officers and some other members" approach rather than "here is everyone", which makes the onus to keep it up to date not so burdensome.

**Comment by maxx1128** [comment]
@bsutt123 What were you thinking of for the "blog of individuals" page you mentioned? Would this be something an active member writes up about themselves and then is shown on the site?

**Comment by bsutt123** [comment]
@maxx1128 Well here is my thought. It may be helpful for people thinking about joining to be able to see some of the people that are actually a part of the group. Maybe we can highlight a couple of the groups officers, and then a couple of the more experienced members who are doing some talks as well as their expertise. This not only give them a chance to get to know some of us,  but also might makes it more likely that they will come to hack night or a study hall, or one of our presentations because we aren't faceless group members anymore.

The intention is not to have everyone on there, and we can be up front that this is not every member of the group, just the ones that want to be highlighted on the site. That should _hopefully_ assuage the concerns that we would have to keep it up to date, because there isn't really any need to add people as they come in, just when you want to add yourself for whatever reason because you are doing presentations or want to be a "teacher" at study hall you can make your own markdown page and we will add it to the site.

I'm not sold that its a great idea, but if the intention of the developers page is to put a face to the name, and make us more human, i think that that is a more clear cut and effective way to do it.

If the goal was something else, or we don't like that goal in general, then I am more than happy just scrapping it. Just trying to think of what the page could be rather than what it currently is.

**Comment by sukima** [comment]
May I suggest as an alternative... A mentors page. Anyone willing to be a New Haven IO mentor would offer a small bio/blog/contact info to newhaven.io and they are listed on a mentor page (Jekyll makes this super easy with the `_data` directory).

This way people can touch base or have a face or two so when attending a meetup have a little sense of familiarity. Maybe ask questions or offer advise. I know that attending new groups it helps to have a point of contact but an organizer or MC already has way too much on their plate to also facilitate some hand holding. A (very loose and self administered) mentor program would take that burden off the MC during events.

It would also offer a more friendly perspective to the NHio website. In other words a page of people who have volunteered to be contacted by other people to help answer questions or simply direct them to the right persons.

**Comment by treznick** [comment]
I'm going to close this since #123 removed the developers page. 

@sukima feel free to file a new issue referencing this one so we can thread conversatin about your proposal for a mentors page.
